logging:
  level:
    netgloo: DEBUG
server:
  port: 8088
spring:
  application:
    name: main-skills-tracker
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/hr
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage:
          engine: innodb

  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
